#Trying New stuff
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
{{- if eq "prod" .Values.RUNTIME_ENV }}
  namespace: prod
{{- else }}
  namespace: default
{{- end }}
data:
  primary.js: |
    db.createUser(
        {
            user: "davinder",
            pwd: "davinderpass",
            roles: [
                {
                    role: "readWrite",
                    db: "students"
                }
            ]
        }
    );

    use students;
    db.studentdata.insertOne({name:'FirstStudent1'})
